FORMAT: 1A

# LRAD

The LRAD API connects LRAD devices to the internet.

## LRAD Collection [/lrads]

### List All LRADs [GET]
This action obtains the list of all LRAD devices in the system.

+ Response 200 (application/json)
    + Attributes (lrad)

### Create a New LRAD [POST]
This action allows you to create a new LRAD. It takes a JSON
object containing at least the IP address of the LRAD.

+ Request (application/json)

        {
            "IpAddress": "192.168.0.10",
        }

+ Response 201 (application/json)

    + Headers

            Location: /lrads/1

    + Body
    + Attributes (lrad)

## LRAD [/lrads/{id}]
An lrad contains state information about the LRAD.


    + Parameters
        + id (number) - ID of the lrad in the form of an integer

    + Attributes (lrad)

### View LRAD Detail [GET]
This action obtains the details of the LRAD with the specified id.

+ Response 200 (application/json)
    + Attributes (lrad)
        
### Delete LRAD [DELETE]
This action deletes the LRAD with the specified id.

+ Response 204

# Data Structures

## lrad (object)
    + Id: 2061810697 (number, required) -  A positive integer between 1 and 100 that represents the unique ID for the LRAD.
    + IpAddress 192.168.1.117 (string, required) - IP address of the LRAD.
    + Type LRAD_MNS (string, required) - The type of LRAD device.
    + Name LRAD1 (string, required) - The name of the LRAD.
    + ConnectionState Connected (string, required) - The LRAD connection state.
    + Volume 75 (number) - The LRAD volume.
    + Latitude 33.017586 (number) - Latitude of the LRAD.
    + Longitude -117.107661 (number) - Longitude of the LRAD.
    + array[Sound] (object)
    + SpeakerState (object)
## Sound (object)
    + Description: (string)
    + Name: (string)
    + Key: (string)
## SpeakerState (object)
    + Attenuation: (number)
    + EndpointVolume: (number)
    + BatteryCharge: (number)
    + AmpStatus: (number)
    + DamStatus: (number)
    + Temperature: (number)
    + AmpCount: (number)
    + DeviceFaults (object)
    + StatusFlags (object)
    + DioAlerts (object)
## DeviceFaults (object)
    + Amp0: (string)
    + Amp1: (string)
    + Amp2: (string)
    + Amp3: (string)
    + BatChargeMonitor: (string)
    + HostComm: (string)
    + WatchdogTimer: (string)
    + Dam: (string, required)
    + TempSensor: (string)
## StatusFlags (object)
    + AmpsOn: (string)
    + DioOn: (string)
    + AudioOn: (string)
    + FansOn: (string)
    + DiagOn: (string)
    + MuteOn: (string)
    + RepeatOn: (string)
    + BatCharging: (string)
## DioAlerts (object)
    + Fan1RotorLocked: (string)
    + Fan2RotorLocked: (string)
    + AlarmSwitch1Active: (string)
    + AlarmSwitch2Active: (string)
    + Mp3PlayerOn: (string)
    + DoorOpen: (string)