FORMAT: 1A

# LRAD
The LRAD API is a RESTful service that connects LRAD devices to the internet.

<!--This is a comment. Comments are not displayed in the browser
## Authentication
Nearly every request to the Wink API requires an OAuth bearer token.
Exceptions to this rule will be documented.
-->

## Content types
Nearly every request to the LRAD API should be expressed as JSON.
Nearly every response from the LRAD API will be expressed as JSON.
Exceptions to this rule will be documented.

## HTTP verbs
The LRAD API uses HTTP verbs in a pretty standard ways:
+ GET for retrieving information without side-effects
+ PUT for updating existing resources, with partial-update semantics supported
+ POST for creating new resources or blind upserts of existing resources
+ DELETE for destructive operations on existing resurces

## Identifiers
All LRAD device objects in the LRAD API can be uniquely identified by a <code>UID</code>.

<!--This is a comment. Comments are not displayed in the browser
## Creatable vs. permanent
The term "creatable" will describe a resource which may be created and/or destroyed by the user.
The term "permanent" will describe a resource which may not be directly created or deleted by a user.
Note that permanent does not imply that the resource will always exist, just that the user may not create or destroy it. Under no circumstances should you assume that a resource will always exist.
-->

<!--This is a comment. Comments are not displayed in the browser
## Mutable vs. immutable
The term "mutable" will describe a resource or attribute which the user may modify at will, assuming the user has the necessary permissions to do so.
The term "immutable" will describe a resouce or attribute which may not be modified directly by the user.
Note that immutable does not imply that the resource or attribute will never change, just that the user may not directly change it. Under no circumstances should you assume that a resource or attribute will always remain the same.
-->

## Error states
The common HTTP Response Status Codes are used.

## LRAD device [/lrad/v1/devices/{uid}{?fields}]
An LRAD device contains state information about the LRAD device specified by the <code>UID</code>.

+ Parameters
    + uid (string) - UID of the specific LRAD device
    + fields (optional) - comma separated list of <code>LradDevice</code> fields to include in the response

### View LRAD device details [GET]
This action obtains the details of the LRAD device with the specified <code>UID</code>.

+ Response 200 (application/json)
    + Attributes (LradDevice)

### Delete LRAD device [DELETE]
This action deletes the LRAD device with the specified <code>UID</code>.

+ Response 204

### Update an existing LRAD device [PUT]
This action allows you to modify the properties of the LRAD device with the specified <code>UID</code>.

+ Request (application/json)

    + Attributes (ConfigurationInfo)

+ Response 201 (application/json)

## LRAD devices [/lrad/v1/devices{?fields,Uid,IpAddress,SubnetMask,IpGatewayAddress,Type,Name,MacAddress,ConnectionState,SatelliteStatus,SpeakerType,Status}]

+ Parameters
    + fields (options) - list of LRAD device fields to return
    + Uid (optional) - A 128-bit UID identifier query variable
    + IpAddress (optional) - IP address query variable
    + SubnetMask (optional) - Subnet mask query variable
    + IpGatewayAddress (optional) - IP gateway address query variable
    + Type (optional) - Type query variable
    + Name (optional) - Name query variable
    + MacAddress (optional) - MAC Address query variable
    + ConnectionState (optional) - Connection state query variable
    + SatelliteStatus (optional) - Satellite status query variable
    + SpeakerType (optional) - Speaker type query variable
    + Status (optional) - Status query variable

### List all LRAD devices [GET]
This action obtains the list of LRAD devices in the collection.

+ Response 200 (application/json)
    + Attributes (array[LradDevice])

### Create a new LRAD device [POST]
This action allows you to add a new LRAD device to the collection. It takes a JSON
object containing at least the IP address of the LRAD device. If not specified,
the <code>Type</code> will default to <code>LRAD_MNS</code> and the <code>UID</code>
will be automatically created.

+ Request (application/json)

    + Attributes
        + IpAddress: 192.168.1.140 (string) - IP address of the device.
        + Latitude: 33.017586 (number) - Latitude of the device.
        + Longitude: 117.107661 (number) - Longitude of the device.
        + Uid: `076580c5-2d58-4bf8-86a3-1e1ebda0647e` (string, required) -  A 128-bit integer number used to uniquely identify a device.
        + Type: LRAD_MNS (string, required) - The type of device (LRAD_MNS).
        + SpeakerType: Double_360X (string) - Type of speaker (unknown, Single_360X, Double_360X, Quad_360X, Eight_360X, Single_360Xm, Double_360Xm, Single_Horn_60, Double_Horn_60, Triple_Horn_60, Quad_Horn_60, RX_1000, RX_500, RXL_500)

+ Response 201 (application/json)

### Update existing LRAD devices [PUT]
This action allows you to modify the properties of the LRAD devices with the specified <code>UID</code>.

+ Request (application/json)

    + Attributes (array[DeviceConfiguration])

+ Response 201 (application/json)

## Discover LRAD devices [/lrad/v1/discovery]

### Initiate LRAD discovery [POST]
This action initiates the LRAD network device discovery process.

+ Response 204
    + Attributes (array[DeviceBase])

### List discovered LRADs [GET]
This action obtains the list of all LRAD devices discovered on the network.

+ Response 200 (application/json)
    + Attributes (array[DeviceBase])

## Group Audio Playback Control
**/lrad/v1/devices/audio** controls audio for groups of LRAD devices.

### Start Audio Message Playback [/lrad/v1/devices/audio/play]
This resource controls sending the specified audio resource to groups of LRAD devices through various transport methods.

#### Start Audio Message Playback [POST]
This action will convert the specified audio message and precrusor sound into a single audio resource at the specified compression
and send it to the LRAD devices with the specified <code>UID(s)</code> at the specified attenuation using the specified transport method.
Audio will be sent to all devices if no UIDs are specified.

+ Request (application/json)
    + Attributes
        + Uids (array[Uid], optional) - An array of UIDs specifying the devices to which the audio resource will be streamed. The audio resource will be streamed to all devices if no UIDs are specified.
        + RepeatCount: 1 (number, optional) - The number of times to repeat the audio message resource.
        + VoiceMessage (AudioResource, required) - The audio message resource to play on the specified devices.
        + PrecursorSound (AudioResource, optional) - The precursor sound audio resource that is played before the VoiceMessage resource.

+ Response 204

### Stop Audio Playback  [/lrad/v1/devices/audio/stop]
This resource stops audio playback for groups of LRAD devices.

#### Stop Audio Playback [POST]
This action stops all audio playback for the LRAD device with the specified <code>UID(s)</code>.
Null attributes will stop all playback.

+ Request (application/json)
    + Attributes
        + Uids (array[Uid], optional) - An array of UIDs specifying the devices to stop audio playback. The audio playback will be stopped on all devices if no UIDs are specified.

+ Response 204

## Group Remote Audio Control
**/lrad/v1/devices/audio/remote** controls the audio resources stored remotely on LRAD devices.

### Initiate Remote Audio Playback  [/lrad/v1/devices/audio/remote/play]
This resource controls the playback of remote audio files for groups of LRAD devices.

#### Play Remote Audio [POST]
This action initiates remote audio file playback for the specified remote audio files on the LRAD devices
with the specified <code>UID(s)</code> at the specified attenuation and repeat state.

+ Request (application/json)
    + Attributes (array[RemoteAudioPlayback])

+ Response 204

### Remote Audio File Management  [/lrad/v1/devices/audio/remote/files]
This resource updates the audio files stored on groups of LRAD devices.

#### Transfer Remote Audio File [PUT]
This action transfers an audio resource to the LRAD devices with the specified <code>UID(s)</code>.

+ Request (application/json)
    + Attributes
        + Uids (array[Uid], optional) - An array of UIDs specifying the devices to which the audio file will be transfered. The audio file will be transferred to all devices if no UIDs are specified.
        + AudioResource (AudioResource, required) - The audio resource to be transferred to the specified devices.
        + Name: alert.wav (string) - Name of the file that the audio message will be saved.

+ Response 204

#### Delete Remote Audio Files [DELETE]
This action deletes audio file from the LRAD devices with the specified <code>UID(s)</code>.

+ Request (application/json)
    + Attributes
        + Uids (array[Uid]) - An array of UIDs specifying the devices to delete the audio file(s). The audio file(s) will be deleted on all devices if no UIDs are specified.
        + FileName (string, required) - name of file to delete.

+ Response 204

## Group Audio Stream Control
**/lrad/v1/devices/audio/stream** controls audio streams for groups of LRAD devices.

### Initiate Audio Stream from Resource  [/lrad/v1/devices/audio/stream/play]
This resource controls streaming an embedded audio resource to groups of LRAD devices.

#### Play audio stream from resource [POST]
This action will stream the specified audio resource to the LRAD devices with the specified
<code>UID(s)</code> at the specified attenuation and repeat. Audio will be sent to all devices if no UIDs are specified.

+ Request (application/json)
    + Attributes
        + Uids (array[Uid], optional) - An array of UIDs specifying the devices to which the audio resource will be streamed. The audio resource will be streamed to all devices if no UIDs are specified.
        + AudioResource (AudioResource, required) - The audio resource to be streamed to the specified devices.
        + Attenuation: 0 (number, optional) - Attenuation in dB to apply to the maximum audio driver volume (0 to -103).
        + RepeatOn: false (boolean, optional) - Audio repeat state.

+ Response 204

### Audio Stream File Management  [/lrad/v1/devices/audio/stream/files]
This resource controls audio stream file resources on the REST API server.

#### Transfer audio file for streaming [PUT]
This action transfers an audio file to the REST API server.
Note that either the Resource or the Uri attribute must be specified but not both.

+ Request (application/json)
    + Attributes
        + AudioResource (AudioResource, required) - The audio resource to be saved on the REST API server.
        + Name: alert.wav (string, required) - Name of the file.

+ Response 204

#### Delete audio stream files [DELETE]
This action deletes the specified audio file(s) from the REST API server.

+ Request (application/json)
    + Attributes
        + Names (array[FileName], required) - Array of file names to delete.

+ Response 204

#### List all audio stream files [GET]
This action obtains the list of audio files names on the REST API server that can be used for streaming.

+ Response 200 (application/json)
    + Attributes
        + Names (array[FileName], required) - Array of file names that can be used for streaming.

### Initiate Audio Stream from File  [/lrad/v1/devices/audio/stream/files/play]
This resource controls streaming a REST API server audio file to groups of LRAD devices.

#### Play audio stream from file [POST]
This action will stream the audio file from the REST API server to the LRAD devices with the specified
<code>UID(s)</code> at the specified attenuation and repeat. Audio will be sent to all devices if no UIDs are specified.

+ Request (application/json)
    + Attributes
        + Uids (array[Uid], optional) - An array of UIDs specifying the devices to which the audio resource will be streamed. The audio resource will be streamed to all devices if no UIDs are specified.
        + FileName: `alert.mp3` (string, required) - The file name of audio message to be streamed to the specified devices.
        + Attenuation: 0 (number, optional) - Attenuation in dB to apply to the maximum audio driver volume (0 to -103).
        + RepeatOn: false (boolean, optional) - Audio repeat state.

+ Response 204

# Group Asynchronous Updates

**Objects that can be received asynchronously over the web socket connection**

## DevicePropertyChanged (object)
This object contains an array of LRAD device property changed objects. Each object is uniquely identified by the LRAD device <code>UID</code>.

## LRAD device property changed (object)
The LRAD device property changed object contains the collection of properties that have changed for the LRAD device with the specified <code>UID</code>.

These properties are the same as those specified in the LradDevice object (see "View LRAD device details" response).

Only the properties that have changed will be included in the collection. The collection can include any combination of the following objects:

|API field|Attributes|Description|
|----|----|----|
|Uid|(String)|A 128-bit integer number used to uniquely identify a device.|
|IpAddress|(String)|IP address of the device|
|SubnetMask|(String)|Subnet mask of the device|
|IpGatewayAddress|(String)|IP gateway address of the device|
|Type|(String)|The type of device (LRAD_MNS)|
|Name |(String)|The name of the device. (can be blank)|
|MacAddress|(String)|The MAC address of the device (can be blank)|
|ConnectionState|(String)|The device connection state (Not_Connected, Connecting, Conntected)|
|Latitude|(String)|Latitude of the device|
|Longitude|(String)|Longitude of the device|
|SatelliteStatus | (String) | Satellite status (Not_Connected or number of satellites)|
|SpeakerType|(String)| Type of speaker (unknown, Single_360X, Double_360X, Quad_360X, Eight_360X, Single_360Xm, Double_360Xm, Single_Horn_60, Double_Horn_60, Triple_Horn_60, Quad_Horn_60, RX_1000, RX_500, RXL_500)|
|Status|(String)|Overall status of the mass notification system|
|Activity | (String)|tbd|
|Volume|(String)|The device volume|
|MnsState |(object)|state of the MNS device|
## MnsState (object)
|API field|Attributes|Description|
|----|----|----|
|Attenuation|(number)|Attenuation in dB to apply to the maximum audio driver volume (0 to -103)|
|EndpointVolume|(number)| Volume setting for the endpoint audio source (0 to 20)|
|AmpCount|(number)| Number of amplifiers (1 – 4)|
|AmpStatus|(number)| Individual amplifier status bitmap (1 = good, 0 = faulted)|
|DamStatus|(number)|Operational status of the data acquisition module (Inactive, Active, Faulted, Dianostics_Active)|
|BatteryCharge|(number)| Battery charge level (0 – 100 %)|
|Temperature|(number)| Temperature (-128ºC to 127 ºC)|
|StatusFlags|(object)| Object containing state information of the MNS|
|DeviceFaults|(object)|Object containig information about which MNS devices are faulted|
|DioAlerts|(object)| Object containing digital I/O state information|
|AudioFiles|(object)| An array of Audio File objects stored in the MNS device|
|PlaybackStatus|(object)| Object containing playback information for the audio currently playing (only valid if StatusFlags.AudioOn = true)|

## AudioFile (object)
|API field|Attributes|Description|
|----|----|----|
|Name|(String)| Name of the file|
|Key|(String)| The key value assigned to the file|
|Description|(String)| Description of the file|

## PlaybackStatus (object)
|API field|Attributes|Description|
|----|----|----|
|Name|(String)| The current progress through the file|
|Duration|(String)| The duration of the audio file|
|AudioFile|(object)| Object containing audio file information|

## DeviceFaults (object)
|API field|Attributes|Description|
|----|----|----|
|Amp0|(String)| Amplifier unit number 0 fault state|
|Amp1|(String)| Amplifier unit number 1 fault state|
|Amp2|(String)| Amplifier unit number 2 fault state|
|Amp3|(String)| Amplifier unit number 3 fault state|
|BatChargeMonitor|(String)| Battery charge monitor fault state|
|HostComm|(String)| Host communications device fault state|
|WatchdogTimer|(String)| Watchdog timer device fault state|
|Dam|(String)| Data acquisition module fault state|
|TempSensor|(String)| Temperature sensor device fault state|

## StatusFlags (object)
|API field|Attributes|Description|
|----|----|----|
|AmpsOn|(String)| Amplifier power state|
|DioOn|(String)| Digital I/O active state|
|AudioOn|(String)| Audio active state|
|FansOn|(String)| Fans on state|
|DiagOn|(String)| Diagnostics active state|
|MuteOn|(String)| Audio mute state|
|RepeatOn|(String)| Audio repeat state|
|BatCharging|(String)| Battery charging state (true = charging, false = discharging)|

## DioAlerts (object)
|API field|Attributes|Description|
|----|----|----|
|Fan1RotorLocked|(String)| Fan 1 rotor locked state|
|Fan2RotorLocked|(String)| Fan 2 rotor locked state|
|AlarmSwitch1Active|(String)| Alarm 1 switch state|
|AlarmSwitch2Active|(String)| Alarm 2 switch state|
|Mp3PlayerOn|(String)| MP3 player power state|
|DoorOpen|(String)| Enclosure door state (true = door open, false = door closed)|

    + Example of an asynchronous DevicePropertyChanged message:
    
        {
            "DevicePropertyChanged": {
            [{
                "076580c5-2d58-4bf8-86a3-1e1ebda0647e": {
                "IpAddress": "192.168.1.140",
                "Type": "LRAD_MNS",
                "Name": "LRAD1",
                "MacAddress": "01:23:45:67:89:AB",
                "ConnectionState": "Connected",
                "Latitude": 33.017586,
                "Longitude": 117.107661,
                "SatelliteStatus": "Not_Connected",
                "SpeakerType": "Double_360X",
                "Status": "OK",
                "Activity": "none",
                "Volume": 75,
                "MnsState": {
                    "Attenuation": 0,
                    "EndpointVolume": 20,
                    "AmpCount": 2,
                    "AmpStatus": 0,
                    "DamStatus": 0,
                    "BatteryCharge": 0,
                    "Temperature": 40,
                    "StatusFlags": {
                        "AmpsOn": "false",
                        "DioOn": "false",
                        "AudioOn": "false",
                        "FansOn": "false",
                        "DiagOn": "false",
                        "MuteOn": "false",
                        "RepeatOn": "false",
                        "BatCharging": "false"
                    },
                    "DeviceFaults": {
                        "Amp0": "true",
                        "Amp1": "false",
                        "Amp2": "false",
                        "Amp3": "false",
                        "BatChargeMonitor": "false",
                        "HostComm": "false",
                        "WatchdogTimer": "false",
                        "Dam": "false",
                        "TempSensor": "false"
                    },
                    "DioAlerts": {
                        "Fan1RotorLocked": "false",
                        "Fan2RotorLocked": "false",
                        "AlarmSwitch1Active": "false",
                        "AlarmSwitch2Active": "false",
                        "Mp3PlayerOn": "false",
                        "DoorOpen": "false"
                    },
                    "AudioFiles": [{
                        "Name": "alert.wav",
                        "Key": "1",
                        "Description": "default alert"
                    }],
                    "PlaybackStatus": {
                        "Progress": 0,
                        "Duration": 0,
                        "AudioFile": {
                            "Name": "alert.wav",
                            "Key": "1",
                            "Description": "default alert"
                        }
                    }
                }
            },
            {
                "17af4e48-9dc6-4e6f-a105-1ceff7807e28": {
                    "MnsState": {
                        "Attenuation": -3,
                    }
                }
            }]
        }

# Data Structures

## DeviceBase (object)
+ Uid: `076580c5-2d58-4bf8-86a3-1e1ebda0647e` (string, required) -  A 128-bit integer number used to uniquely identify a device.
+ IpAddress: 192.168.1.140 (string, required) - IP address of the device.
+ SubnetMask: 255.255.255.0 (string) - Subnet mask of the device.
+ IpGatewayAddress: 192.168.1.1 (string) - IP gateway address of the device.
+ Type: LRAD_MNS (string, required) - The type of device (LRAD_MNS).
+ Name: LRAD1 (string, required) - The name of the device. (can be blank)
+ MacAddress: 01:23:45:67:89:AB (string, required) - The MAC address of the device (can be blank)

## LradDevice (DeviceBase)
+ ConnectionState: Connected (string, required) - The device connection state (Not_Connected, Connecting, Conntected).
+ Latitude: 33.017586 (number) - Latitude of the device.
+ Longitude: 117.107661 (number) - Longitude of the device.
+ SatelliteStatus: Not_Connected (string) - Satellite status (Not_Connected or number of satellites).
+ SpeakerType: Double_360X (string) - Type of speaker (unknown, Single_360X, Double_360X, Quad_360X, Eight_360X, Single_360Xm, Double_360Xm, Single_Horn_60, Double_Horn_60, Triple_Horn_60, Quad_Horn_60, RX_1000, RX_500, RXL_500)
+ Status: OK (string) - Overall status of the mass notification system
+ Activity: none (string) - tbd 
+ Volume: 75 (number) - The device volume.
+ MnsState (MnsState) - Detailed state information about the mass notification system.

## MnsState (object)
+ Attenuation: 0 (number) - Attenuation in dB to apply to the maximum audio driver volume (0 to -103).
+ EndpointVolume: 20 (number) - Volume setting for the endpoint audio source (0 to 20).
+ AmpCount: 2 (number) - Number of amplifiers (1 – 4).
+ AmpStatus: 0 (number) - Individual amplifier status bitmap (1 = good, 0 = faulted).
+ DamStatus: 0 (number) -  Operational status of the data acquisition module (Inactive, Active, Faulted, Dianostics_Active).
+ BatteryCharge: 0 (number) - Battery charge level (0 – 100 %).
+ Temperature: 40 (number) - Temperature (-128ºC to 127 ºC).
+ StatusFlags (StatusFlags) - Object containing state information of the MNS.
+ DeviceFaults (DeviceFaults) - Object containig information about which MNS devices are faulted.
+ DioAlerts (DioAlerts) - Object containing digital I/O state information.
+ AudioFiles (array[AudioFile]) - An array of Audio File objects stored in the MNS device
+ PlaybackStatus (PlaybackStatus) - Object containing playback information for the audio currently playing (only valid if StatusFlags.AudioOn = true).

## AudioFile (object)
+ Name: alert.wav (string) - Name of the file.
+ Key: 1 (string) - The key value assigned to the file.
+ Description: default alert (string) - Description of the file.

## PlaybackStatus (object)
+ Progress (number) - The current progress through the file.
+ Duration (number) - The duration of the audio file.
+ AudioFile (AudioFile) - Object containing audio file information.

## DeviceFaults (object)
+ Amp0: true (string) - Amplifier unit number 0 fault state.
+ Amp1: false (string) - Amplifier unit number 1 fault state.
+ Amp2: false (string) - Amplifier unit number 2 fault state.
+ Amp3: false (string) - Amplifier unit number 3 fault state.
+ BatChargeMonitor: false (string) - Battery charge monitor fault state.
+ HostComm: false (string) - Host communications device fault state.
+ WatchdogTimer: false (string) - Watchdog timer device fault state.
+ Dam: false (string) - Data acquisition module fault state.
+ TempSensor: false (string) - Temperature sensor device fault state.

## StatusFlags (object)
+ AmpsOn: false (string) - Amplifier power state.
+ DioOn: false (string) - Digital I/O active state.
+ AudioOn: false (string) - Audio active state.
+ FansOn: false (string) - Fans on state.
+ DiagOn: false (string) - Diagnostics active state.
+ MuteOn: false (string) - Audio mute state.
+ RepeatOn: false (string) - Audio repeat state.
+ BatCharging: false (string) - Battery charging state (true = charging, false = discharging).

## DioAlerts (object)
+ Fan1RotorLocked: false (string) - Fan 1 rotor locked state.
+ Fan2RotorLocked: false (string) - Fan 2 rotor locked state.
+ AlarmSwitch1Active: false (string) - Alarm 1 switch state.
+ AlarmSwitch2Active: false (string) - Alarm 2 switch state.
+ Mp3PlayerOn: false (string) - MP3 player power state.
+ DoorOpen: false (string) - Enclosure door state (true = door open, false = door closed).

## RemoteAudioPlayback (object)
+ Uid: `076580c5-2d58-4bf8-86a3-1e1ebda0647e` (string, required) -  A 128-bit integer number used to uniquely identify a device.
+ One Of
    + Key: 1 (string, required) - The key value assigned to the file.
    + Name: alert.wav (string, required) - Name of the file.
+ RepeatOn: false (string) - Audio repeat state.

## ConfigurationInfo (object)
+ IpAddress: 192.168.1.140 (string) - IP address of the device.
+ SubnetMask: 255.255.255.0 (string) - Subnet mask of the device.
+ IpGatewayAddress: 192.168.1.1 (string) - IP gateway address of the device.
+ Name: LRAD1 (string) - The name of the device. (can be blank)
+ Latitude: 33.017586 (number) - Latitude of the device.
+ Longitude: 117.107661 (number) - Longitude of the device.
+ SpeakerType: Double_360X (string) - Type of speaker (unknown, Single_360X, Double_360X, Quad_360X, Eight_360X, Single_360Xm, Double_360Xm, Single_Horn_60, Double_Horn_60, Triple_Horn_60, Quad_Horn_60, RX_1000, RX_500, RXL_500)

## DeviceConfiguration (ConfigurationInfo)
+ Uid: `076580c5-2d58-4bf8-86a3-1e1ebda0647e` (string, required) -  A 128-bit integer number used to uniquely identify a device.

## Uid (object)
+ Uid: `076580c5-2d58-4bf8-86a3-1e1ebda0647e` (string, required) -  A 128-bit integer number used to uniquely identify a device.

## FileName (object)
+ Name: alert.wav (string) - Name of the file.

## AudioResource (object)
+ MimeType: mp3 (string, required) - Specifies the format of the audio file. https://www.iana.org/assignments/media-types/media-types.xhtml#audio
+ Size: 1001124 (number, optional) - The integer indicating the size of the resource file
+ Digest: C73EF97F8EFAB61ABF00B165B00205F4FB097250 (string, optional) - The code representing the digital digest [hash] computed from the resource file
+ One Of
    + Resource: `//tQxAAAAAAAAAAAAAAAAAAAAAAASW5mbwAAAA8AAA3NAAtE5AADBQgKDRASFBcaHB8hIycpLC4wNDY4Oz1AQ0VHSk1PUlRWWlxfYWNnaWtucHN2eHp9g` (string, required) - The base-64 encoded data content of the resource file [DerefUri]
    + Uri: `https://storage-tts.alertsense.com/tts-generated-audio/8ef68871877c9787c31bd28cfe3f9f25.mp3` (string, required) -  The identifier of the hyperlink for the resource file