FORMAT: 1A
HOST: http://lrad.apiblueprint.org/

# LradDeviceServer

The LradDeviceServer API connects LRAD devices to the internet.

## Speaker Collection [/speakers]

### List All Speakers [GET]

+ Response 200 (application/json)

        {
            "speakers": [{
                "Longitude": "-117.107661",
                "ConnectionState": "Connected",
                "Sounds": [{
                    "Description": "",
                    "Name": "alert.wav",
                    "Key": "Alert"
                }, {
                    "Description": "",
                    "Name": "2KHz.wav",
                    "Key": "2KHzTone"
                }, {
                    "Description": "",
                    "Name": "diag.wav",
                    "Key": "diagnostic"
                }],
                "Latitude": "33.017586",
                "SpeakerState": {
                    "Status": {
                        "Attenuation": 0,
                        "EndpointVolume": 15,
                        "DeviceFaults": {
                            "Amp2": false,
                            "BatChargeMonitor": true,
                            "HostComm": false,
                            "Amp1": false,
                            "WatchdogTimer": false,
                            "Dam": true,
                            "Amp3": false,
                            "TempSensor": false,
                            "Amp0": false
                        },
                        "StatusFlags": {
                            "AmpsOn": false,
                            "DioOn": false,
                            "AudioOn": false,
                            "FansOn": false,
                            "DiagOn": false,
                            "MuteOn": false,
                            "RepeatOn": false,
                            "BatCharging": false
                        }
                    },
                    "StatusDetails": {
                        "BatteryCharge": 0,
                        "AmpStatus": 0,
                        "DioAlerts": {
                            "Fan2RotorLocked": false,
                            "AlarmSwitch2Active": false,
                            "Mp3PlayerOn": false,
                            "AlarmSwitch1Active": false,
                            "Fan1RotorLocked": false,
                            "DoorOpen": true
                        },
                        "DamStatus": 0,
                        "Temperature": 0,
                        "AmpCount": 2
                    }
                },
                "Volume": "75",
                "Id": 2061810697,
                "IpAddress": "192.168.30.117",
                "Type": "LRAD_MNS",
                "Name": "LRAD-1"
            }]
        }
        
## Speaker [/speaker/id]

### Get Speaker [GET]

+ Response 200 (application/json)

        {
            "speakers": [{
                "Longitude": "-117.107661",
                "ConnectionState": "Connected",
                "Sounds": [{
                    "Description": "",
                    "Name": "alert.wav",
                    "Key": "Alert"
                }, {
                    "Description": "",
                    "Name": "2KHz.wav",
                    "Key": "2KHzTone"
                }, {
                    "Description": "",
                    "Name": "diag.wav",
                    "Key": "diagnostic"
                }],
                "Latitude": "33.017586",
                "SpeakerState": {
                    "Status": {
                        "Attenuation": 0,
                        "EndpointVolume": 15,
                        "DeviceFaults": {
                            "Amp2": false,
                            "BatChargeMonitor": true,
                            "HostComm": false,
                            "Amp1": false,
                            "WatchdogTimer": false,
                            "Dam": true,
                            "Amp3": false,
                            "TempSensor": false,
                            "Amp0": false
                        },
                        "StatusFlags": {
                            "AmpsOn": false,
                            "DioOn": false,
                            "AudioOn": false,
                            "FansOn": false,
                            "DiagOn": false,
                            "MuteOn": false,
                            "RepeatOn": false,
                            "BatCharging": false
                        }
                    },
                    "StatusDetails": {
                        "BatteryCharge": 0,
                        "AmpStatus": 0,
                        "DioAlerts": {
                            "Fan2RotorLocked": false,
                            "AlarmSwitch2Active": false,
                            "Mp3PlayerOn": false,
                            "AlarmSwitch1Active": false,
                            "Fan1RotorLocked": false,
                            "DoorOpen": true
                        },
                        "DamStatus": 0,
                        "Temperature": 0,
                        "AmpCount": 2
                    }
                },
                "Volume": "75",
                "Id": 2061810697,
                "IpAddress": "192.168.30.117",
                "Type": "LRAD_MNS",
                "Name": "LRAD-1"
            }]
        }

### Create a New Speaker [POST]

You may a speaker using this action. It takes a JSON
object containing at least the IP address of the speaker.

+ Request (application/json)

        {
            "IpAddress": "192.168.0.10",
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "speaker": {
                    "IpAddress": "192.168.30.38",
                    "Name": "OEK-CP-LRAD-6",
                    "ConnectionState": "Not_Connected",
                    "Id": 1713476742,
                    "Type": "LRAD_MNS"
                }
            }